# Generated by Django 4.0.3 on 2022-04-05 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Employes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('last_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='todo.skill', verbose_name='Квалификация')),
                ('special', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='todo.special', verbose_name='Специальность')),
            ],
        ),
    ]
